### ISSUE TITLE
Repo and html needs a lot of clean up

### ISSUE THREAD

**Issue by karthik** [datacarpentry/R-ecology#14]
So I've been poking around this repo and have been trying to make sense of all the clutter. There is lots of legacy stuff ported over from SWC without any clean plan. 

**What works**  

The Makefile is well written and does everything as far as updating lessons. 

**What doesn't work**

* The titles from all rendered html pages are "Learning objectives"
* There is no template called "topic"
* The font is too small (13px could easily be 15px)
* We could use a different syntax highlighter (more static one) to make it easier to read and copy text. See [a ropensci tutorial](https://ropensci.org/tutorials/alm_tutorial.html) for what I mean.
* The `knitr` opts does not differentiate between code comments and output. This can be fixed with something like:

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(
  comment = "#>"
)
````
* We might also consider adding a more readable web font (perhaps a free Google web font).

Would it be worthwhile to gut this repo and delete everything but the `Rmd` + Makefile and make an actual topic template? Thoughts?

**Comment by fmichonneau** [comment]
I think at this stage that the repo holds the template from Software Carpentry but this lesson doesn't take advantage of it as we rely exclusively on the default options from rmarkdown/knitr to render the lessons. Therefore, I agree we could greatly improve the general look and feel of the lessons.

Given that it seems we are opting to generate the pages in html directly for the R related lessons, I don't think it makes sense to use the Software Carpentry lesson template here. We can use similar guidelines on how the content should be arranged and how the lessons should be structured, but the styling could be made independently.

I agree with all your suggestions, and if we can recycle some of the components rOpenSci uses to style the tutorials, I think the lessons would look much better.

I will also add that it would be nice to add a way to include solutions to challenges that would be hidden at first but that would be displayed on the click of a button "show the solution".

**Comment by tracykteal** [comment]
We have templating for Markdown, but not for RMarkdown. So, we do need to fix this. 

Is the plan to have Rmarkdown and then run the Makefile to generate the HTML? I know we were moving away from having to compile, but it's good to have the Rmarkdown so that both the code and the results of the code are in the file. So, I guess I'm asking for us to establish process. Then we can have the template and apply it to the lessons.

**Comment by tracykteal** [comment]
Also, we do need to get rid of the supp files and the r-ggplot2 directory. So an overall cleanup is needed.

**Comment by ethanwhite** [comment]
> Is the plan to have Rmarkdown and then run the Makefile to generate the HTML? I know we were moving away from having to compile, but it's good to have the Rmarkdown so that both the code and the results of the code are in the file.

My general feeling on this is that their are two decent ways to go. 1. Everything is in markdown and we get the advantages of a nice simple process that is clean standard Jekyll. 2. If we want to be able build Rmarkdown files (and ProjectJupyter notebooks, etc.) then I think we're better off just using SWC's system as it stands. This seems like it's probably beyond the scope of this issue, so if we're thinking about using Rmarkdown here then I think we should have a broader discussion about the build process in general.

**Comment by fmichonneau** [comment]
It seems that they are two tangled concepts in this issue.

* We need to compile the Rmarkdown to generate the markdown file. This is done with R (with the `knitr` package). I think it would be a mistake to only use markdown for the R lessons, as using Rmarkdown ensures that all the code we include in the lesson is going to work. The current price we have to pay for this is that we need to keep both the Rmarkdown and the markdown files under version control, with the consequence that contributors might edit the markdown files instead of the Rmarkdown files, or that the Rmarkdown files get edited without being recompiled and get out of sync with the markdown. PR review should catch these issues. Another approach would be to use Travis-CI to take care of this compilation such that the markdown files generated from the Rmarkdown files would always be up to date. It seems like it would require some up front time investment but could make things easier in the future.

* The second issue is what we do with the markdown files. Currently, Software Carpentry compiles the markdown files to HTML using pandoc. Even if the decision is not finalized it's likely that they will move away from pandoc and use jekyll, and it's also what we are working towards. However, previously (in particular for earlier workshops), the Makefile was also generating the HTML files from the Rmarkdown files.

Maybe one reason these two concepts are tangled is that the current Makefile go straight from the Rmarkdown files to the HTML files (and generates the markdown files in the process). However, it could easily be modified to only generate the Markdown files that will be used by Jekyll. We could use this approach before experimenting with building the pages using Travis.

I would also suggest to open separate issues for the suggestions @karthik initially proposed.

**Comment by fmichonneau** [comment]
I think the issues raised here have either been fixed or captured in other issues.
