### ISSUE TITLE
Confusing instructions in 02-starting-with-data.Rmd

### ISSUE THREAD

**Issue by karthik** [datacarpentry/R-ecology#15]
There is first:

> We are going to use the R function download.file() to download the CSV file that contains the survey data from figshare, and we will use read.csv() to load into memory (as a data.frame) the content of the CSV file:

Then 

> if (!require("curl")) {
  install.packages("curl")
}
library("curl")
curl_download("https://dl.dropboxusercontent.com/u/22808457/portal_data_joined.csv",
              "data/portal_data_joined.csv")

I don't know if most people can easily install the curl package on their windows machines. Also not sure why we need to deal with `https` at this time (one more layer of overload). Can't we post the surveys file somewhere non-https and use base R's `download.file` that everyone has?

```
# e.g.
download.file("http://inundata.org/surveys.csv", destfile = "surveys.csv")
```

**Comment by karthik** [comment]
Also it's terribly confusing that there is a file named `surveys.csv` and also `portal_data_joined.csv` with similar data.

Could we simplify?
Also rename the files maybe since most people wont know what portal means.

**Comment by fmichonneau** [comment]
The data on Dropbox is a temporary fix while waiting for the data used by the dplyr lesson to make its way to the figshare repository that holds the rest of the data (figshare allow downloading over http contrary to dropbox). We could use the native libcurl support that comes with R 3.2.0 instead of using the curl package while this gets resolved, but I am also not opposed to having it on another server (like yours) so we can download it over http.

If it makes sense, the entire lesson could be re-written to only use `portal_data_joined.csv` dataset instead of surveys, but it seems that first, we would need to write the script that converts the original data to the `portal_data_joined.csv` so it can be incorporated with the rest of the datasets. Thus, we don't multiply versions of the dataset, and can document how the `portal_data_joined.csv` was generated.

cc'ing @karawoo  and @naupaka who might be able to chime in on how to recreate the dataset.

**Comment by naupaka** [comment]
The `portal_data_joined.csv` was just the three tables (species, surveys, plots) joined in SQL.  Would be easy enough to use dplyr to do the joins straight from the SQLite file at the top of the file before the rest of the lesson starts. 

Pedagogically, the idea for doing it this way was that students had spent the previous day working in Excel, OpenRefine, and SQLite to clean the data, build the database, and then the `portal_data_joined.csv` is the output of those efforts.  Might be a nice segue way to  move from doing all of that in the Firefox plugin to just having it live in the R code to start the lesson.  Here's the SQL we used to do it:

```SQL
# Join all 3 tables, don't duplicate species_id or plot_id
SELECT sur.*, sp.genus, sp.species, sp.taxa, pl.plot_type
FROM surveys AS sur
JOIN species AS sp ON sur.species_id = sp.species_id
JOIN plots AS pl ON sur.plot_id = pl.plot_id
```

Would it make sense to have the dplyr version of this at the top of this lesson?

**Comment by fmichonneau** [comment]
Thanks @naupaka!

As long as the narrative in the lessons is clear that we move from the messy dataset in Excel, to a cleaner version in SQL through OpenRefine, I am not too concerned that we start with the dplyr way of doing in the R lesson. I would actually suggest that this gets done in the "how to use SQL from R" lesson that Ted had put together.

My main concern is that the process on how to programmatically generate this dataset from the original data is documented here https://github.com/weecology/portal-teachingdb and that the dataset is made available in the figshare repository http://figshare.com/articles/Portal_Project_Teaching_Database/1314459

I also thought that Kara had mentioned that some filtering was done such that only sexes scored M and F were kept, and records with missing lengths and weights were removed.

**Comment by karawoo** [comment]
I believe we replaced the non-M and F sexes as part of the OpenRefine portion of the lesson, but I don't think we removed observations with missing lengths and weights.

**Comment by naupaka** [comment]
All of the fixes we made with OpenRefine to each of the three tables are documented in the json files [here](https://github.com/datacarpentry/2015-05-14-wsu/tree/gh-pages/Workshop_Files/data/cleaned). I think this gets back to the earlier question about having a canonical set of 'messed up' files to clean during a workshop vs starting from clean files (e.g. those currently hosted on figshare).

**Comment by tracykteal** [comment]
Thanks @naupaka and @karawoo I like using the joined cleaned up data here, both for how it works in the lesson and for the narrative. Although sometimes R is being taught before SQL for the practical reason that one instructor is teaching R and so it needs to be split in to two different days, so they won't necessarily go through the SQL join section yet. 

@naupaka had suggested setting up an overall workshop repo where we can keep track of these things and discuss the narrative. I just set it up at https://github.com/datacarpentry/workshop-ecology  That would be a place where we can keep the SQL and JSON used to modify the dataset. 

Also, I think the currently used messy data set https://www.dropbox.com/s/iq3og1ihke3a82x/survey_data_tabs.xls?dl=0
has been pretty well vetted, so we might consider downloading it to the FigShare collection. Ideally a learner will download all the data used for the workshop at the beginning of day 1 in one package. 

There can be a backup link in the R lesson that will download it straight from FigShare though.

**Comment by naupaka** [comment]
I think another thing to think about is what sort of messed up data are useful to teach the OpenRefine features vs. e.g. Excel. 

I agree that the current messed up data that @tracykteal mentioned and linked to is great for the Excel part of the lessons, but I think OpenRefine really excels at handling large datasets with small typos in categorical columns, weird numeric outliers, etc. Those datasets, which I tweaked from the full, raw tables (taken from FigShare) are [here in the WSU repository](https://github.com/datacarpentry/2015-05-14-wsu/tree/gh-pages/Workshop_Files/data/raw/tofix).  These are the datasets that the JSON cleanup steps were taken on.  If the workshop doesn't decide to teach OpenRefine, then these are much less useful (or perhaps not useful at all). For example, I could see a series that starts with the messy Excel file, discuss that, then use SQL and R on the not-messy data (the clean tables currently on FigShare), and skip OpenRefine altogether.  

I think the trick is that there isn't quite yet a mechanism or place to put full-2-day ordered series of lessons together (since the lessons are now mostly modular and interchangeable in terms of ordering). I'm not sure where this might go -- for example a 2-day lesson plan that had data and lesson order bult to work together. Perhaps in an instructor markdown file with links in the workshop repo @tracykteal just made? I could foresee a number of different 'flavors' for workshops, even within a disciplinary focus like ecology.

**Comment by fmichonneau** [comment]
To summarize:

- [x] the issue of using complex code to download files over https: we now ask participants to come to workshops with a recent version of R (at least 3.2.2) that provides native support of https.
- [x] most of the lesson now uses `portal_data_joined.csv` so I think there is no confusion between this file and `surveys.csv` (at least, it hasn't come up in any of the workshops I have taught recently)
- [x] we have a messy spreadsheet that works well for the spreadsheet lesson and that is available on FigShare with the other data files
- [x] I created an issue with the OpenRefine lesson datacarpentry/openrefine-ecology#10 to suggest we use the files Naupaka created
